name = "ameza-website"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]
